package com.cn.point

import com.cn.point.PointDomain;

rule subBackNumsPoint
	// 发生退货，扣减10分
	salience 10
	lock-on-active true
	when
		$pointDomain : PointDomain(backNums >= 5)
	then
		$pointDomain.setPoint($pointDomain.getPoint()-10);
		$pointDomain.recordPointLog($pointDomain.getUserName(),"subBackNumsPoint");
end

rule subBackMondyPoint
	// 退货金额大于100，扣减100分
	salience 11
	lock-on-active true
	when
		$pointDomain : PointDomain(backMondy >= 100)
	then
		$pointDomain.setPoint($pointDomain.getPoint()-10);
		$pointDomain.recordPointLog($pointDomain.getUserName(),"退货金额记录");
end